image:
  file: .gitpod.Dockerfile

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:

# Parallel task
- name: rust setup
  openMode: split-left
  init: cargo build
  command: cargo run

# Parallel task
- name: pre-commit setup
  openMode: split-right
  init: |
      pre-commit install
      pre-commit install-hooks

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
- port: 6080
  onOpen: open-preview


vscode:
  extensions:
    # Rust Extension Pack
    - pinage404.rust-extension-pack
    # Even Better TOML
    - tamasfe.even-better-toml
